language: python
job:
  include:
    #- python: "3.8"
    #  env: 
    #    - TOXENV=py38
    #- python: "3.9"
    #  env: 
    #    - TOXENV=py39
    - python: "3.10"
      dist: focal
    
    - python: "3.11"
      dist: bionic
    
    - python: "3.10"
      dist: focal
    
  - linux






